STA556 Homework 2: Housing Market Analysis

Part 1: Read an external data source

Documentation:

In [1]:
#Import the packages needed for loading csv file

import pandas as pd
import numpy as np

housing_market = pd.read_csv("../data/raw/housing_market.csv")

Analyzing the qualities of the data frame.

In [2]:
housing_market.head()

,ListingID,City,Neighborhood,PropertyType,Condition,Bedrooms,Bathrooms,SqFt,LotSize_sqft,Age_years,GarageSpaces,ListPrice,PricePerSqFt,DaysOnMarket,ListingDate
0,L00001,Riverside,Oakwood,Condo,Good,1,1.0,507,0,1,1,292438,576.80,9,2022-07-11
1,L00002,Riverside,Oakwood,Condo,Good,1,2.5,632,0,3,0,317167,501.85,62,2022-07-18
2,L00003,Crestwood,Lakeside,Condo,Fair,2,2.0,1094,0,2,0,314962,287.90,50,2023-04-22
3,L00004,Riverside,Eastside,Condo,Good,1,1.5,657,0,58,0,242939,369.77,9,2023-03-26
4,L00005,Dunmore,Cedar Ridge,Single Family,Fair,3,3.5,1784,4726,19,2,302631,169.64,32,2023-06-23

In [3]:
housing_market.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ListingID     1500 non-null   str
 1   City          1500 non-null   str
 2   Neighborhood  1500 non-null   str
 3   PropertyType  1500 non-null   str
 4   Condition     1500 non-null   str
 5   Bedrooms      1500 non-null   int64
 6   Bathrooms     1500 non-null   float64
 7   SqFt          1500 non-null   int64
 8   LotSize_sqft  1500 non-null   int64
 9   Age_years     1500 non-null   int64
 10  GarageSpaces  1500 non-null   int64
 11  ListPrice     1500 non-null   int64
 12  PricePerSqFt  1500 non-null   float64
 13  DaysOnMarket  1500 non-null   int64
 14  ListingDate   1500 non-null   str
dtypes: float64(2), int64(7), str(6)
memory usage: 175.9 KB

In [4]:
housing_market.describe()

,Bedrooms,Bathrooms,SqFt,LotSize_sqft,Age_years,GarageSpaces,ListPrice,PricePerSqFt,DaysOnMarket
count,1500.00000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1.500000e+03,1500.000000,1500.000000
mean,3.07600,2.188667,1631.756000,3132.665333,20.966000,1.260667,5.113979e+05,335.789200,32.703333
std,1.19799,0.734460,602.603748,2462.357408,19.487997,0.923736,2.409705e+05,152.989111,37.993161
min,1.00000,1.000000,446.000000,0.000000,1.000000,0.000000,1.376830e+05,98.260000,1.000000
25%,2.00000,1.500000,1183.000000,0.000000,7.000000,1.000000,3.244522e+05,217.030000,10.000000
50%,3.00000,2.000000,1613.000000,3138.500000,15.000000,1.000000,4.479060e+05,303.625000,21.000000
75%,4.00000,2.500000,2051.750000,4645.250000,30.000000,2.000000,6.604575e+05,427.870000,41.000000
max,6.00000,4.000000,3802.000000,11660.000000,105.000000,3.000000,1.635664e+06,1089.600000,365.000000

In [5]:
housing_market.dtypes

ListingID           str
City                str
Neighborhood        str
PropertyType        str
Condition           str
Bedrooms          int64
Bathrooms       float64
SqFt              int64
LotSize_sqft      int64
Age_years         int64
GarageSpaces      int64
ListPrice         int64
PricePerSqFt    float64
DaysOnMarket      int64
ListingDate         str
dtype: object

In [6]:
housing_market.columns

Index(['ListingID', 'City', 'Neighborhood', 'PropertyType', 'Condition',
       'Bedrooms', 'Bathrooms', 'SqFt', 'LotSize_sqft', 'Age_years',
       'GarageSpaces', 'ListPrice', 'PricePerSqFt', 'DaysOnMarket',
       'ListingDate'],
      dtype='str')

In [7]:
housing_market.isna().sum()

ListingID       0
City            0
Neighborhood    0
PropertyType    0
Condition       0
Bedrooms        0
Bathrooms       0
SqFt            0
LotSize_sqft    0
Age_years       0
GarageSpaces    0
ListPrice       0
PricePerSqFt    0
DaysOnMarket    0
ListingDate     0
dtype: int64

Observations: 
Note: For Lot size, condos have a 0 so fill with NA since condos do not have lots

Part 2: Modular Cleansing

In [8]:
#Import functions from python script:
import sys
from pathlib import Path
sys.path.append(str(Path("../src").resolve()))

from processing_cleaning import(
    fill_na,
    get_non_na_rows,
    get_columns
)

In [9]:
#First fill in 0's in LotSize_sqft with NA's for condos 
filled_df= fill_na(data = housing_market, column_name = "LotSize_sqft", value =0)